services:
  app:
    build: .
    env_file:
      - .env.local
    ports:
      - "${APP_BIND_IP}:${APP_PORT}:${APP_PORT}"
    restart: unless-stopped

  redis:
    image: redis:8.0
    env_file:
      - .env.local
    restart: always
    ports:
      - "${APP_BIND_IP}:${REDIS_PORT}:${REDIS_PORT}"

  mongo:
    image: mongo:8.0
    env_file:
      - .env.local
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: "${MONGODB_DATABASE}"
    ports:
      - "${APP_BIND_IP}:${MONGODB_PORT}:${MONGODB_PORT}"
    volumes:
      - mongo_data:/data/db
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro

volumes:
  mongo_data: